server:
  port: 7000
spring:
  datasource:
      url: jdbc:h2:file:~/zagrosz_db
      username: SA
      password: password123
      driver-class-name: org.h2.Driver
      continueOnError: true
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: classpath:database/changelog.xml